test: test-sequence test-starting-block

test-sequence:
	cd .. && python -m framework.tests.sequence_example

test-starting-block:
	cd .. && python -m framework.tests.init_procedure_example

clean:
	rm -rf *.pyc */*.pyc
