test: test-sequence test-starting-block test-ax12-starting-block

test-sequence:
	cd .. && python -m framework.tests.sequence_example

test-starting-block:
	cd .. && python -m framework.tests.init_procedure_example

test-ax12-starting-block:
	cd .. && python -m framework.tests.ax12_with_jack_test

clean:
	rm -rf *.pyc */*.pyc
